config/routes.rb
require 'sidekiq/web'

SearchServer::Application.routes.draw do
  resources :prices

  resources :file_imports, :only => [:show, :index]

  resources :search_audits, :only => [:index, :show]

  resources :system_versions

  resources :purchasing_systems

  devise_for :users

  resources :products do

    resources :product_attributes, :only => :new

    member do
      get 'review'
      get 'details'
    end
    collection do
      get 'upload_form', :as => 'upload_form'
      post 'upload', :as => 'upload'
      get 'search', :as => 'search'
    end
  end

  resources :agreements do
    resources :products, :only => :index
  end

  resources :suppliers

  resources :clients

  resources :users, :path => "systemusers"

  match 'search' => 'search#search'

  root :to => redirect('/users/sign_in')

  mount Sidekiq::Web, at: '/sidekiq'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    if user.admin?
      can :manage, :all
      cannot :destroy, Agreement
      cannot :destroy, Client
      cannot :destroy, Supplier
    elsif user.buyer?
      can [:upload_form, :upload], Product
      can :read, Product
      can :search, Product
      can [:read, :update], Client, :id => user.administratable_id if user.administratable_type == Client.to_s
      can [:read, :create, :update], Agreement, :client_id => user.administratable_id if user.administratable_type == Client.to_s
      can [:read, :create, :update], User do |u|
        (user.administratable_type == Client.to_s && user.administratable.users.map{|x|x.id}.include?(u.id))||(user.administratable_type == u.administratable_type && user.administratable_id == u.administratable_id)
      end

      can :read, Supplier

    elsif user.supplier?
      can [:upload_form, :upload], Product
      can :search, Product
      can [:destroy], Product do |p|
        user.administratable.agreements.any?{|a| p.agreements.any?{|aa| a == aa }} 
      end
      can [:read, :create, :update], Product do |p|
        user.administratable.agreements.any?{|a| p.agreements.any?{|aa| a == aa }} 
      end

      can [:read, :update], Agreement, :supplier_id => user.administratable_id if user.administratable_type == Supplier.to_s
      can [:read, :create, :update], User do |u|
        (user.administratable_type == Supplier.to_s && user.administratable.users.map{|x|x.id}.include?(u.id))||(user.administratable_type == u.administratable_type && user.administratable_id == u.administratable_id)
      end
      can [:read, :update], Supplier, :id => user.administratable_id if user.administratable_type == Supplier.to_s

    end
    # :read, :create, :update and :destroy
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/client.rb
# == Schema Information
#
# Table name: clients
#
#  id                   :integer          not null, primary key
#  name                 :string(255)
#  ac_number            :string(255)
#  authentication_key   :string(255)
#  category_schema      :string(255)
#  account_status       :string(255)
#  comment              :text
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#  deleted_at           :time
#  purchasing_system_id :integer
#  system_version_id    :integer
#

class Client < ActiveRecord::Base
  include Administratable

  acts_as_paranoid

  encrypted_id key: '584acfdbf83bd1009f1bf376bcaceb710'

  # This is the buyer
  attr_accessible  :name, :authentication_key, :purchasing_system_id, :system_version_id, :category_schema

  has_many :users, :as => :administratable
  has_many :agreements
  belongs_to :purchasing_system
  belongs_to :system_version

  validates :name, 
      :length => { :maximum => 200 },
      :presence => true
  validates :authentication_key, 
      :presence => true

  scope :including_purchasing_system, includes(:purchasing_system)
  scope :including_system_version, includes(:system_version)

  before_create :generate_ac_number

  after_update :update_index_for_prices
  after_destroy :destroy_index_for_agreements
 
private

  def generate_ac_number
    begin
      self.ac_number = Array.new(10){|i|rand(10)}.join
    end while Supplier.find_by_ac_number(self.ac_number).present?
  end

  def destroy_index_for_agreements
    agreements.each { |agreement| agreement.destroy_index_for_prices }
  end

  def update_index_for_prices
    agreements.each { |agreement| agreement.update_index_for_prices }
  rescue
    puts "Exception was thrown"
  end

end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  load_and_authorize_resource

  # GET /clients
  # GET /clients.json
  def index
    @deleted_clients = Client.only_deleted if current_user.admin?
    @clients = Client.scoped.including_purchasing_system.including_system_version

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @clients }
    end
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
    @client = Client.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @client }
    end
  end

  # GET /clients/new
  # GET /clients/new.json
  def new
    @client = Client.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @client }
    end
  end

  # GET /clients/1/edit
  def edit
    @client = Client.find(params[:id])
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(params[:client])

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render json: @client, status: :created, location: @client }
      else
        format.html { render action: "new" }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /clients/1
  # PUT /clients/1.json
  def update
    @client = Client.find(params[:id])

    respond_to do |format|
      if @client.update_attributes(params[:client])
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client = Client.find(params[:id])
    @client.destroy

    respond_to do |format|
      format.html { redirect_to clients_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def edit_path_if_can object
    link_to 'Edit', [:edit, object] if can?( :update, object)
  end
  def action_isnt_blacklisted(action, blacklist)
    !action_is_blacklisted action, blacklist
  end
  def action_is_blacklisted action, blacklist
    blacklist.present? && blacklist.include?(action  )
  end
  def sort_link_to(entity, field, label = nil)
    label ||= field.to_s.titleize
    direction = sort_field == field.to_s && sort_direction == "asc" ? "desc" : "asc"
    css_class = (field.to_s == sort_field) ? "current #{sort_direction}" : nil
    link_to label, {:sort_field => field.to_s, :sort_direction => direction}, :class => css_class
  end
end

app/helpers/products_helper.rb
module ProductsHelper
  def display_price(product, user)
    if user.admin?
      "#{product.price_range.begin} .. #{product.price_range.end}"
    elsif user.buyer? || user.supplier?
      product.prices_for( user.administratable).to_a.map{|p|p.price}
    end
  end

  def prices(product, user)
    if user.admin?
      product.prices
    elsif user.buyer? || user.supplier?
      product.prices_for( user.administratable)
    end
  end
end

app/views/clients/_form.html.haml
= simple_form_for(@client) do |f|
  = f.input :name
  - unless @client.new_record?
    = f.input :ac_number, disabled: true
  = f.input :authentication_key
  = f.association :purchasing_system, include_blank: false
  .select.optional.input
    = f.label :system_version_id
    = f.grouped_collection_select :system_version_id, PurchasingSystem.order(:name), :system_versions, :name, :id, :name, include_blank: false
  = f.input :category_schema, collection: ['UNSPSC'], include_blank: false
  - unless @client.new_record?
    = f.input :account_status, disabled: true
  = f.button :submit

app/views/clients/_list.html.haml
%h1= title
%table.admin_table
  %thead
    %th Name
    %th AC number
    %th Authentication Key
    %th Purchasing System
    %th System Version
    %th Category Schema
    %th Nr of agreements
    %th Account Status
    %th
    %th
    %th
  %tbody
    - source.each do |client|
      %tr{:class => cycle("odd", "even")}
        %td= client.name
        %td= client.ac_number
        %td= client.authentication_key
        %td= client.purchasing_system.name rescue ''
        %td= client.system_version.name rescue ''
        %td= client.category_schema
        %td= client.agreements.count
        %td= client.account_status
        - if client.deleted?
          %td
          %td= link_to 'Resurect', '#'
          %td
        - else
          = render :partial => 'shared/list_actions', :locals => {object: client}
%br/

app/views/clients/edit.html.haml
%h1 Editing buyer

= render 'form'

= link_to 'Show', @client
- unless current_user.buyer?
  |
  = link_to 'Back', clients_path

app/views/clients/index.html.erb
<%= render :partial => "list", :locals => { title: 'Listing buyers', source: @clients } %>

<%= link_to 'New Buyer', new_client_path %>

<% if current_user.admin? && @deleted_clients.count > 0%>
    <%= render :partial => "list", :locals => { title: 'Archived buyers', source: @deleted_clients } %>
<% end %>

app/views/clients/new.html.erb
<h1>New buyer</h1>

<%= render 'form' %>

<%= link_to 'Back', clients_path %>

app/views/clients/show.html.haml
%p#notice= notice
%p
  %b Name:
  = @client.name
%p
  %b Ac Number:
  = @client.ac_number
%p
  %b Authentication Key:
  = @client.authentication_key
%p
  %b Purchasing System:
  = @client.purchasing_system.name rescue ''
%p
  %b System Version:
  = @client.system_version.name rescue ''
%p
  %b Category Schema:
  = @client.category_schema
%p
  %b Nr of agreements:
  = link_to @client.agreements.count, agreements_path
%p
  %b Account Status:
  = @client.account_status
%p
  %b Comment:
  = @client.comment
= link_to 'Edit', edit_client_path(@client)
- unless current_user.buyer?
  |
  = link_to 'Back', clients_path